// @generated by scripts/gen-safety-modes.mjs from openapi.json — do not edit.
//
// The safety mode each endpoint on the administrative surface requires (see the
// SAFE spec). Declared once on the handler's `routes!` entry in the Rust
// source; regenerated by `just gen-openapi`.

import type { SafetyMode } from "./safety";

/** The mode each endpoint requires, keyed as `module/fn`. */
export const SAFETY_MODES: Readonly<Record<string, SafetyMode>> = Object.freeze({
	"admins/add": "danger",
	"admins/delete": "danger",
	"admins/list": "read-only",
	"inventory_variables/for_group": "read-only",
	"inventory_variables/remove": "write",
	"inventory_variables/set": "write",
	"mcp_tokens/list": "read-only",
	"mcp_tokens/mint": "danger",
	"mcp_tokens/revoke": "danger",
	"safety/lower": "read-only",
	"safety/raise": "read-only",
	"safety/session": "read-only",
	"sql/execute_query": "read-only",
	"sql/get_last_user_query": "read-only",
	"sql/get_query_history": "read-only",
	"sql/is_sql_available": "read-only",
});
